# This is a basic workflow to help you get started with Actions

name: sync-data

# Controls when the workflow will run
on:
  schedule:
    - cron: "00 11 * * *"  # Allows you to run this workflow manually from the Actions tab
    
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        # 使用专用的 Python 环境设置 Action
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # 指定您需要的 Python 版本

      - name: Install dependencies
        # 现在您可以使用配置好的 Python 环境运行 pip
        run: |
          python -m pip install --upgrade pip
          pip install modelscope

      - uses: robinraju/release-downloader@v1
        with:
          repository: 'chenditc/investment_data'
          latest: true
          fileName: 'qlib_bin.tar.gz'

      - name: Upload to modelscope dataset
        env:
          MODELSCOPE_TOKEN: ${{ secrets.MODELSCOPE_TOKEN }}
        run: |
          modelscope login --token="$MODELSCOPE_TOKEN"
          modelscope upload jzhongsun/qlib-data ./qlib_bin.tar.gz qlib_bin.tar.gz --repo-type dataset

      - uses: magdemajt/trigger-webhook@v1
        env:
          WEBHOOK_URL: ${{ secrets.BUILD_WEBHOOK_URL }}
        with:
          url: "$WEBHOOK_URL"
          json: '{"foo": "bar"}' # optional
          headers: '{"Content-Type": "application/json"}' # optional           
